import {chromium} from 'playwright';import fs from 'node:fs/promises';import assert from 'node:assert/strict';
const browser=await chromium.launch({executablePath:process.env.BROWSER_EXECUTABLE,channel:process.env.BROWSER_EXECUTABLE?undefined:(process.env.BROWSER_CHANNEL||'msedge'),headless:true});const results=[];
async function run(name,options,setup,check){const page=await browser.newPage(options);const errors=[];page.on('pageerror',e=>errors.push(e.message));await setup?.(page);await page.goto('http://127.0.0.1:4188/3d-study.html');await check(page);assert.deepEqual(errors,[]);results.push({name,pass:true});await page.close();}
const desktop={viewport:{width:1440,height:1000}};
await run('desktop model + all stages + pause + still',desktop,null,async p=>{await p.waitForSelector('[data-state="ready"]');for(let i=0;i<6;i++){await p.locator(`[data-story-step="${i}"]`).scrollIntoViewIfNeeded();await p.waitForTimeout(450);}await p.getByRole('button',{name:'Pause product motion'}).click();assert.equal(await p.locator('[data-product-scene]').getAttribute('data-rendering'),'false');await p.getByRole('button',{name:'Resume product motion'}).click();await p.waitForTimeout(100);assert.equal(await p.locator('[data-product-scene]').getAttribute('data-rendering'),'true');await p.getByRole('button',{name:'Use still image'}).click();assert.equal(await p.locator('[data-product-scene]').getAttribute('data-state'),'static');assert.equal(await p.locator('[data-product-scene] canvas').count(),0);});
await run('offscreen suspension',desktop,null,async p=>{await p.waitForSelector('[data-state="ready"]');await p.locator('footer').scrollIntoViewIfNeeded();await p.waitForTimeout(700);assert.equal(await p.locator('[data-product-scene]').getAttribute('data-rendering'),'false');});
for(const [name,options] of [['phone',{viewport:{width:390,height:844}}],['reduced motion',{...desktop,reducedMotion:'reduce'}]])await run(name,options,null,async p=>{await p.waitForTimeout(1000);assert.equal(await p.locator('[data-product-scene] canvas').count(),0);assert.equal(await p.evaluate(()=>performance.getEntriesByType('resource').some(e=>e.name.endsWith('.glb'))),false);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);});
await run('WebGL creation failure',desktop,async p=>p.addInitScript(()=>{const original=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...args){if(type==='webgl2'||type==='webgl')return null;return original.call(this,type,...args);};}),async p=>{await p.waitForSelector('[data-reason="initialization-failed"]');assert.equal(await p.locator('.product3d-fallback').isVisible(),true);});
await run('model request failure',desktop,async p=>p.route('**/*.glb',r=>r.abort()),async p=>{await p.waitForSelector('[data-reason="initialization-failed"]');assert.equal(await p.locator('[data-product-scene] canvas').count(),0);});
await run('context loss fallback',desktop,null,async p=>{await p.waitForSelector('[data-state="ready"]');await p.locator('[data-product-scene] canvas').evaluate(c=>c.dispatchEvent(new Event('webglcontextlost',{cancelable:true})));await p.waitForSelector('[data-reason="context-lost"]');assert.equal(await p.locator('[data-product-scene] canvas').count(),0);});
await run('JavaScript disabled remains usable',{...desktop,javaScriptEnabled:false},null,async p=>{assert.equal(await p.getByRole('heading',{name:'Small rituals. Beautiful days.'}).isVisible(),true);assert.equal(await p.locator('.product3d-fallback').isVisible(),true);assert.equal(await p.locator('#collection').count(),1);});
await run('existing product dialogs and CTA',{...desktop,reducedMotion:'reduce'},null,async p=>{await p.getByRole('link',{name:'Explore the collection'}).first().click();assert.ok(p.url().endsWith('#collection'));for(const id of ['balm','soap','lotion']){await p.locator(`button[data-product="${id}"]`).last().click();await p.waitForSelector('#product-dialog[open]');await p.keyboard.press('Escape');assert.equal(await p.locator('#product-dialog').isVisible(),false);}assert.equal(await p.locator('.product-grid').count(),3);});
await run('low memory avoids 3D',desktop,async p=>p.addInitScript(()=>Object.defineProperty(navigator,'deviceMemory',{get:()=>2})),async p=>{await p.waitForTimeout(800);assert.equal(await p.locator('[data-product-scene]').getAttribute('data-quality'),'static');assert.equal(await p.evaluate(()=>performance.getEntriesByType('resource').some(e=>e.name.endsWith('.glb'))),false);});
await run('hidden document suspension (simulated visibility event)',desktop,null,async p=>{await p.waitForSelector('[data-state="ready"]');await p.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,get:()=>true});document.dispatchEvent(new Event('visibilitychange'));});assert.equal(await p.locator('[data-product-scene]').getAttribute('data-rendering'),'false');await p.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,get:()=>false});document.dispatchEvent(new Event('visibilitychange'));});await p.waitForTimeout(100);assert.equal(await p.locator('[data-product-scene]').getAttribute('data-rendering'),'true');});
await browser.close();await fs.writeFile('docs/browser-tests.json',JSON.stringify(results,null,2));console.log(results);


