import {chromium}from'playwright';import fs from'node:fs/promises';import assert from'node:assert/strict';
const b=await chromium.launch({channel:'msedge'}),results=[];const p=await b.newPage({viewport:{width:1440,height:1000}});const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:4188');await p.waitForFunction(()=>+document.querySelector('.coast-motion').dataset.frames>2);
let info=await p.locator('.coast-motion').evaluate(c=>{const e=c.environment,ctx=c.getContext('2d'),a=ctx.getImageData(0,0,c.width,c.height).data;let protectedMax=0;for(let y=0;y<c.height;y++)for(let x=0;x<c.width;x++){if(y/c.height>.4||Math.hypot(x/c.width-.5,y/c.height-.312)<.214)protectedMax=Math.max(protectedMax,a[(y*c.width+x)*4+3]);}return {protectedMax,frames:+c.dataset.frames,kind:e.kind,videoPlaying:!e.video().paused};});assert.equal(info.protectedMax,0);assert.equal(info.videoPlaying,true);results.push({test:'hero product/label/wood pixels protected',...info});
await p.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,get:()=>true});document.dispatchEvent(new Event('visibilitychange'));});assert.equal(await p.locator('.coast-motion').evaluate(c=>c.environment.video().paused),true);await p.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,get:()=>false});document.dispatchEvent(new Event('visibilitychange'));});results.push({test:'hidden document pauses video (simulated event)',pass:true});
await p.getByRole('button',{name:'Pause scene',exact:true}).click();let frames=await p.locator('.coast-motion').getAttribute('data-frames');await p.waitForTimeout(300);assert.equal(await p.locator('.coast-motion').getAttribute('data-frames'),frames);assert.equal(await p.locator('.coast-motion').evaluate(c=>c.environment.video().paused),true);await p.getByRole('button',{name:'Play scene',exact:true}).click();
await p.getByRole('button',{name:'SHOP TALLOW BALM',exact:true}).click();await p.waitForSelector('#product-dialog[open]');await p.keyboard.press('Escape');results.push({test:'pause/resume and shop dialog',pass:true});
for(const [id,f,period,selector]of [['soap',.5,24,'.ambient-motion'],['lotion',.9,16,'.ambient-motion']]){await p.evaluate(f=>{document.documentElement.style.scrollBehavior='auto';const s=document.querySelector('.scene-scroll');scrollTo(0,s.getBoundingClientRect().top+scrollY+(s.offsetHeight-innerHeight)*f)},f);await p.waitForTimeout(250);const data=await p.locator(`.product-${id} .product-visual ${selector}`).evaluate((c,{id,period})=>{const e=c.environment,ctx=c.getContext('2d');e.render(0);const first=ctx.getImageData(0,0,c.width,c.height).data;e.render(period/4);const other=ctx.getImageData(0,0,c.width,c.height).data;e.render(period);const last=ctx.getImageData(0,0,c.width,c.height).data;let diff=0,seam=0,protectedMax=0;for(let y=0;y<c.height;y++)for(let x=0;x<c.width;x++){const i=(y*c.width+x)*4,u=x/c.width,v=y/c.height;const protectedPixel=id==='soap'?v>=.32:(v>.28&&v<.81)||Math.hypot((u-.814)/.125,(v-.115)/.125)<1||Math.hypot((u-.36)/.07,(v-.115)/.08)<1;if(protectedPixel)protectedMax=Math.max(protectedMax,other[i+3]);for(let k=0;k<4;k++){diff+=Math.abs(first[i+k]-other[i+k]);seam+=Math.abs(first[i+k]-last[i+k]);}}const t=performance.now();for(let i=0;i<20;i++)e.render(i/20);return {meanChanged:diff/first.length,seamMean:seam/first.length,protectedMax,renderMs:(performance.now()-t)/20};},{id,period});assert.equal(data.protectedMax,0);assert.ok(data.seamMean<.001);assert.ok(data.meanChanged>.01);results.push({test:id+' full periodic cycle, protected pixels and render cost',...data});}
assert.equal(await p.locator('.coast-motion').evaluate(c=>c.environment.video().paused),true);results.push({test:'hero offscreen video paused',pass:true});await p.close();
for(const mode of ['reduced','save-data','video-error','phone']){const page=await b.newPage({viewport:mode==='phone'?{width:390,height:844}:{width:1440,height:1000},reducedMotion:mode==='reduced'?'reduce':'no-preference'});if(mode==='save-data')await page.addInitScript(()=>Object.defineProperty(navigator,'connection',{value:{saveData:true,addEventListener(){}}}));if(mode==='video-error')await page.route('**/*.mp4',r=>r.abort());const media=[];page.on('request',r=>{if(r.url().endsWith('.mp4'))media.push(r.url());});await page.goto('http://127.0.0.1:4188');await page.waitForTimeout(1300);if(mode==='reduced'||mode==='save-data'){assert.equal(media.length,0);assert.equal(await page.locator('.coast-motion').isVisible(),false);}if(mode==='video-error')assert.equal(await page.locator('.coast-motion').isVisible(),false);assert.equal(await page.locator('.coast-photo').isVisible(),true);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);if(mode==='phone'){await page.screenshot({path:'outputs/motion/phone-after.png'});assert.ok(+await page.locator('.coast-motion').getAttribute('data-frames')>2);}results.push({test:mode,pass:true,mediaRequests:media.length});await page.close();}assert.deepEqual(errors,[]);await b.close();await fs.writeFile('docs/environment-motion-tests.json',JSON.stringify(results,null,2));console.log(results);

