import {NodeIO} from '@gltf-transform/core';
import {ALL_EXTENSIONS} from '@gltf-transform/extensions';
import {dedup,prune,weld,meshopt,textureCompress} from '@gltf-transform/functions';
import {MeshoptEncoder,MeshoptDecoder} from 'meshoptimizer';
import sharp from 'sharp';
import fs from 'node:fs/promises';
await MeshoptEncoder.ready;
const io=new NodeIO().registerExtensions(ALL_EXTENSIONS).registerDependencies({'meshopt.encoder':MeshoptEncoder,'meshopt.decoder':MeshoptDecoder});
const doc=await io.read('assets/3d/exports/tallow-balm.raw.glb');
await doc.transform(dedup(),weld(),prune(),textureCompress({encoder:sharp,targetFormat:'webp',quality:92,resize:[1024,1024]}));
await io.write('assets/3d/exports/tallow-balm.portable.glb',doc);
await doc.transform(meshopt({encoder:MeshoptEncoder,level:'medium'}));
await fs.mkdir('dist/assets/3d',{recursive:true});
await io.write('dist/assets/3d/tallow-balm.v1.glb',doc);
await fs.copyFile('dist/assets/3d/tallow-balm.v1.glb','assets/3d/exports/tallow-balm.optimized.glb');
await sharp('assets/3d/previews/tallow-balm-hero.png').resize({width:900}).webp({quality:90}).toFile('dist/assets/3d/tallow-balm-static.v1.webp');
const files=['assets/3d/source/tallow-balm.blend','assets/3d/exports/tallow-balm.raw.glb','assets/3d/exports/tallow-balm.portable.glb','dist/assets/3d/tallow-balm.v1.glb','dist/assets/3d/tallow-balm-static.v1.webp'];
const report={files:Object.fromEntries(await Promise.all(files.map(async p=>[p,(await fs.stat(p)).size]))),textureBytes:doc.getRoot().listTextures().reduce((n,t)=>n+(t.getImage()?.byteLength||0),0),meshCount:doc.getRoot().listMeshes().length,materials:doc.getRoot().listMaterials().length,notes:'Meshopt preserves smooth geometry and component pivots; WebP quality 92 preserves original label pixels. KTX2 evaluated but not selected: three small labels do not justify decoder/transcoder overhead. No Draco needed alongside Meshopt. Raw/portable exports retained for interchange; only optimized GLB and static WebP ship.'};
await fs.writeFile('docs/asset-payload.json',JSON.stringify(report,null,2));console.log(report);
